repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.3.0
    hooks:
      - { id: trailing-whitespace }
      - { id: end-of-file-fixer }
      - { id: check-docstring-first }
      - { id: check-json }
      - { id: check-yaml }
      - { id: check-merge-conflict }
      - { id: debug-statements }
      - { id: mixed-line-ending, args: ["--fix=no"] }
      - { id: no-commit-to-branch, args: ["--branch", master] }
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.64.5
    hooks:
      - id: golangci-lint
        args: [--config=.golang-ci.yaml]
  - repo: local
    hooks:
      - id: validate-openapi-schema
        name: Validate OpenAPI schema
        language: docker_image
        files: openapi.yml
        entry: redocly/openapi-cli:v1.0.0-beta.108 lint
