version: '3.3'
services:
  api:
    image: go-server:1.0.0
    build: .
    restart: always
    environment:
      - SERVICE_TYPE=API
    ports:
      - 8000:8000
    networks:
      - local-net

  worker:
    image: go-server:1.0.0
    build: .
    restart: always
    environment:
      - SERVICE_TYPE=WORKER
    networks:
      - local-net

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./my-db:/var/lib/mysql
      # - ./mysqlsampledatabase.sql:/var/mysqlsampledatabase.sql
    networks:
      - local-net

volumes:
  esdata:

networks:
  local-net: