version: '3.3'
services:
  api:
    image: agusmazzeo1/reporter:1.0.0
    build: .
    restart: always
    environment:
      - SERVICE_TYPE=API
    ports:
      - 8000:8000
    networks:
      - local-net

  worker:
    image: agusmazzeo1/reporter:1.0.0
    build: .
    restart: always
    environment:
      - SERVICE_TYPE=WORKER
    networks:
      - local-net

  postgres-db:
    image: pgvector/pgvector:pg16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - 5440:5432
    expose:
      - '5440'
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - local-net

volumes:
  esdata:

networks:
  local-net:
