---
service:
  type: API
databases:
  elasticsearch:
    host: 127.0.0.1
    port: 9200
    index: listing
    type: listing
    username: myusername
    password: mypassword

  sql:
    host: 127.0.0.1
    port: 5440
    database: db
    username: user
    password: pass
    driver: postgres

externalClients:
  esco:
    baseUrl: https://clientes.criteria.com.ar/uniwa/api
    tokenUrl: https://clientes.criteria.com.ar/uniwa/api/token
    clientID: Unisync
    username: icastagno
    password: Messiusa24!
