---
databases:
  elasticsearch:
    host: 127.0.0.1
    port: 9200
    index: listing
    type: listing
    username: myusername
    password: mypassword
  
  sql:
    host: 127.0.0.1
    port: 3306
    database: db
    username: user
    password: password
    driver: mysql
    # connection_string: "Server=localhost;Database=mydatabase;User Id=myuser;Password=mypassword;"