databases:
  sql:
    host: 127.0.0.1
    port: 5440
    database: postgres
    username: user
    password: pass
    driver: postgres

service:
  type: "API"
  port: "8080"

logger:
  level: "debug"
  file: "test.log"
