externalClients:
  esco:
    categoryMapFile: /settings/configFiles/denominaciones.csv
databases:
  redis:
    host: db-valkey-nyc3-12653-do-user-16224847-0.f.db.ondigitalocean.com
    port: 25061
    database: 0
    username: default
    password: AVNS_qabJhF6rX2DF9TBu3dC
  sql:
    host: db-postgresql-nyc3-64708-do-user-16224847-0.f.db.ondigitalocean.com
    port: 25060
    database: defaultdb
    username: doadmin
    password: AVNS_d4IvgqZTx_R1nz19xTU
    driver: postgres
    sslmode: require
