name: Go CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: docker/compose:1.29.1

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.4

    - name: Install pre-commit
      run: |
        sudo apt-get install python3-pip -y
        pip3 install pre-commit

    - name: Run pre-commit
      run: pre-commit run

    - name: Test
      run: make test
